// This file was auto-generated by prisma-generator-typescript-interfaces

export type ExerciseCategory = "WEIGHT" | "FREE_WEIGHT" | "CARDIO" | "TIME" | "REPS";

export type WorkoutPlanLevel = "BEGINNER" | "INTERMEDIATE" | "ADVANCED";

export type WorkoutPlanCategory = "STRENGTH" | "ENDURANCE" | "BALANCE" | "FLEXIBILITY" | "LOOSE_WEIGHT";

export interface Language {
  id: string;
  name: string;
  isDefault: boolean;
  createdAt: Date;
  updatedAt: Date;
  texts?: Text[];
  Translation?: Translation[];
}

export interface Text {
  id: number;
  key: string;
  originalText: string;
  language?: Language;
  languageId: string;
  translations?: Translation[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Translation {
  id: number;
  text?: Text;
  textId: number;
  language?: Language;
  languageId: string;
  content: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface User {
  id: number;
  email: string;
  name: string;
  gender: string | null;
  age: number | null;
  password: string;
  createdAt: Date;
  updatedAt: Date;
  Exercise?: Exercise[];
  ExerciseLog?: ExerciseLog[];
  WorkoutPlan?: WorkoutPlan[];
  avatar: string | null;
}

export interface Post {
  id: number;
  titleKey: string;
  contentKey: string | null;
  published: boolean | null;
  authorId: number | null;
}

export interface MuscleGroup {
  id: number;
  parentId: number | null;
  nameKey: string;
  slug: string;
  image: string;
  exercises?: Exercise[];
}

export interface Exercise {
  id: number;
  nameKey: string;
  descriptionKey: string;
  category: ExerciseCategory;
  primaryMuscle?: MuscleGroup[];
  createdBy?: User;
  createdById: number;
  images: string[];
  createdAt: Date;
  updatedAt: Date;
  ExerciseLog?: ExerciseLog[];
  Workout?: Workout | null;
  workoutId: number | null;
  notesKey: string | null;
}

export interface ExerciseLog {
  id: number;
  exercise?: Exercise;
  exerciseId: number;
  user?: User;
  userId: number;
  date: Date;
  repetitions: number;
  weight: number | null;
  notes: string | null;
}

export interface WorkoutPlan {
  id: number;
  nameKey: string;
  cover_image: string | null;
  descriptionKey: string | null;
  level: WorkoutPlanLevel | null;
  isPublic: boolean | null;
  isPremium: boolean | null;
  isFeatured: boolean | null;
  isSingle: boolean | null;
  category: WorkoutPlanCategory;
  workouts?: Workout[];
  createdBy?: User;
  createdById: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Workout {
  id: number;
  nameKey: string;
  exercises?: Exercise[];
  order: number | null;
  createdAt: Date;
  updatedAt: Date;
  WorkoutPlan?: WorkoutPlan;
  workoutPlanId: number;
}
