// make sure better auth server is running
GET {{BASE_URL}}/api/auth/ok

POST {{BASE_URL}}/api/auth/sign-in/email

{
  "email": "bao1@gmail.com",
  "password": "123456#@Nn",
  "rememberMe": false,
  "callbackURL": ""
}


POST {{BASE_URL}}/api/auth/sign-up/email
{
  "name": "ttt",
  "email": "phuongbao14@gmail.com",
  "password": "123456789",
  "callbackURL": ""
}

{{
  // $global.accessToken=response.parsedBody.data.token;
}}

POST {{BASE_URL}}/api/auth/sign-out

GET {{BASE_URL}}/auth/session
Authorization: Bearer {{$global.accessToken}}

GET {{BASE_URL}}/auth/profile
Authorization: Bearer {{$global.accessToken}}

POST {{BASE_URL}}/auth/forgot-password
{
  "email": "bao3@gmail.com"
}