POST {{BASE_URL}}/auth/login

{
  "email": "bao1@gmail.com",
  "password": "123456#@Nn"
}

{{
  $global.accessToken=response.parsedBody.data.accessToken;
  $global.refreshToken=response.parsedBody.data.refreshToken;
}}

POST {{BASE_URL}}/auth/signup

{
  "name": "Bao bao",
  "email": "bao100@gmail.com",
  "password": "123456#@Nn"
}

{{
  $global.accessToken=response.parsedBody.data.accessToken;
  $global.refreshToken=response.parsedBody.data.refreshToken;
}}

GET {{BASE_URL}}/auth/session
Authorization: Bearer {{$global.accessToken}}

GET {{BASE_URL}}/auth/profile
Authorization: Bearer {{$global.accessToken}}
