POST {{BASE_URL}}/exercises
Authorization: Bearer {{$global.accessToken}}
Accept-Language: en
{
  "name": "leg press 3",
  // "notes": "Chest Press notes",
  "category": "WEIGHT",
  "primaryMuscleIds": [5],
  "images": ["https://picsum.photos/200/300"]
  // "description": "Chest Press description"
  // "id": 101
  // "translations": [
  //   {
  //     "language": "en",
  //     "name": "Chest Press",
  //     "description": "Chest Press description"
  //   }
  // ]

}

### Update Exercise

PATCH {{BASE_URL}}/exercises/1
Authorization: Bearer {{$global.accessToken}}
{
  "name": "Chest Press 2",
  "description": "Chest Press description",
  "category": "WEIGHT",
  "muscleGroups": [1]
}


### Get All Exercises
GET {{BASE_URL}}/exercises?muscleGroupId=5
# Authorization: Bearer {{$global.accessToken}}

### Get All Exercises with search
GET {{BASE_URL}}/exercises?limit=15&search=Voluntarius
Authorization: Bearer {{$global.accessToken}}

### Get Exercise by Id
GET {{BASE_URL}}/exercises/4
Authorization: Bearer {{$global.accessToken}}

### Delete Exercise

DELETE {{BASE_URL}}/exercises/6
Authorization: Bearer {{$global.accessToken}}
