POST {{BASE_URL}}/muscle-groups
Authorization: Bearer {{$global.accessToken}}
{
  "nameKey": "muscleGroup.test-1.name",
  "slug": "test-1",
  "image": "https://via.placeholder.com/150",
  "parentId": 2
}

### Get All Muscle Groups
GET {{BASE_URL}}/muscle-groups
Authorization: Bearer {{$global.accessToken}}
Accept-Language: vi

### Get exercise by muscle group

GET {{BASE_URL}}/muscle-groups/5/exercises
Authorization: Bearer {{$global.accessToken}}
Accept-Language: vi