POST {{BASE_URL}}/muscle-groups
Authorization: Bearer {{$global.accessToken}}
{
  "name": "leg",
  "parentId": 2,
  "slug": "leg"
}

### Get All Muscle Groups
GET {{BASE_URL}}/muscle-groups
Authorization: Bearer {{$global.accessToken}}

### Get exercise by muscle group
GET {{BASE_URL}}/muscle-groups/5/exercises
Authorization: Bearer {{$global.accessToken}}