POST {{BASE_URL}}/workouts
Authorization: Bearer {{$global.accessToken}}
{
  "name": "Chest day",
  "workoutPlanId": 1,
  "exerciseIds": [1]
}


### Get all workouts by workout plan id
GET {{BASE_URL}}/workouts/plan/1
Authorization: Bearer {{$global.accessToken}}


###
GET {{BASE_URL}}/workouts/3
Authorization: Bearer {{$global.accessToken}}

GET {{BASE_URL}}/workouts/f363bd5e-479e-4a04-8f44-c9e2d6be8d96

GET {{BASE_URL}}/workouts/1ee2315c-5a1a-42f4-8bf3-f8342127b018

