GET {{BASE_URL}}/workout-session/history
Accept-Language: vi

{{
  $global.workoutSessionId=response.parsedBody.data[2].id;
}}


###

GET {{BASE_URL}}/workout-session/detail?id={{$global.workoutSessionId}}
Accept-Language: vi

GET {{BASE_URL}}/workout-session/detail?id=244bbc32-1b09-4885-a05c-aa3f27eaafd2
Accept-Language: vi

DELETE {{BASE_URL}}/workout-session/{{$global.workoutSessionId}}