POST {{BASE_URL}}/workout-plans
Authorization: Bearer {{$global.accessToken}}
{
  "name": "Workout Plan 1"
}

### ------------------------------------------------------------ find many

###
GET {{BASE_URL}}/workout-plans
Authorization: Bearer {{$global.accessToken}}
Accept-Language: vi
{{
  $global.planId=response.parsedBody.data[0].id;
}}

# get my plans
GET {{BASE_URL}}/workout-plans/user/me
Authorization: Bearer {{$global.accessToken}}

# get by category: STRENGTH ENDURANCE BALANCE FLEXIBILITY LOOSE_WEIGHT
GET {{BASE_URL}}/workout-plans?category=ENDURANCE
Authorization: Bearer {{$global.accessToken}}

# get by featured
GET {{BASE_URL}}/workout-plans?isFeatured=true
Authorization: Bearer {{$global.accessToken}}

# get single plans
GET {{BASE_URL}}/workout-plans?isSingle=true
Authorization: Bearer {{$global.accessToken}}

# get workout plans in groups
GET {{BASE_URL}}/workout-plans/in-groups
Authorization: Bearer {{$global.accessToken}}

### ------------------------------------------------------------ find one
###
GET {{BASE_URL}}/workout-plans/{{$global.planId}}
Authorization: Bearer {{$global.accessToken}}

GET {{BASE_URL}}/workout-plans/651f63fb-4b24-4126-8787-5cf791a41eaa
Authorization: Bearer {{$global.accessToken}}

### ------------------------------------------------------------ delete one
###
DELETE {{BASE_URL}}/workout-plans/1
Authorization: Bearer {{$global.accessToken}}
