Hversion: '3.5'

services:
  postgres:
    container_name: gymapp-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: gymapp
      POSTGRES_USER: bao
      POSTGRES_PASSWORD: 3246
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gymapp-backend
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: gymapp-backend-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
